### ISSUE TITLE
Broken for Ubuntu on Windows

### ISSUE THREAD

**Issue by deanveloper** [alyyousuf7/twenty48#2]
```
 ><>  ~ > twenty48 -width=8 -height=8                  
panic: invalid argument

goroutine 1 [running]:
main.startGame(0x8, 0x8)
        /home/24G/go/src/github.com/alyyousuf7/twenty48/cmd/twenty48/game.go:13 +0x1bc
main.main()
        /home/24G/go/src/github.com/alyyousuf7/twenty48/cmd/twenty48/main.go:28 +0x58
```

```
 ><>  ~ > go env                                                                      
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/[user]/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/[user]/go"
GORACE=""
GOROOT="/usr/lib/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build611790322=/tmp/go-build -gno-record-gcc-switches"
```

Hopefully that's enough info

**Comment by dasper** [comment]
I get the same error but it looks like it is with a dependency rather than the author's code:
https://github.com/nsf/termbox-go/issues/174

The program works fine on cmd and powershell on Windows

**Comment by alyyousuf7** [comment]
Keeping the issue opened until the bug in `termbox` is fixed or we move to some other library.

Thanks @deanveloper for reporting the issue, and @dasper for helping me out :)
